# Machine Learning
_(by Standford University)_

**WEEK 1**

Course of introduction to machine learning offered by Standford University on [Coursera.org](https://www.coursera.org/learn/machine-learning). These are **notes** and **comments** based on lectures and assignments.

The IPython kernel of choice is *Octave* since many exercises and assignments have been devised for that language.

## Definitions and Terminology

- Machine learning is the field of study that gives computers the ability to learn without being explicitly programmed (A. Samuel, 1959);
- A computer program is said to learn from experience _E_ with respect to some task _T_ and some performance measure _P_, if its performance on _T_, as measured by _P_, improves with _E_. (T. Mitchell, 1998).

_e.g.: a spam recognition program in an e-mail client has spam/non-spam classification as task T, watching the user labelling e-mails as experience E and the no. of correctly classified e-mails as performance P._

_e.g.: a chess playing program has the task T of playing chess, through the experience E gained by playing many games and the performance P given by the probability of winning the current game._

## Types of Machine Learning Algorithms

### Supervised Machine Learning

- the "right answers" are given to the algorithm
- we ask the algorithm to produce more "right answers"

_e.g.: a regression problem such as housing price prediction given some input data (size, position, etc.)._

_e.g.: a classification problem such as the prediction of malignant vs. benign tumors using medical data (tumor size, age of the patient, etc.)._

Algorithms can also deal with an infinite no. of features describing the output labels (Support Vector Machines) using a mathematical trick.

### Unsupervised Machine Learning

- data are not labelled
- we ask the algorithm to find some structure to the data

_e.g.: Google News groups similar news stories into topics and then shows them to the user grouped by topic._

_e.g.: using genome information of individuals, we can find clusters of people based on the representation of some genes._

_e.g.: using marketing information we can group customers into segments and offer them better suited offers. We do not know in advance their preferences._

## Algorithms and Cost Function - Introduction

### Vocabulary

- input data are usually called _features_;
- output data can usually be referred to as _targets_ or _labels_;
- the function that learns the task is usually called _hypothesis_ (and indicated as _h_).

### A First Example: Linear Regression

- predict continuous output;
- use a univariate/linear model for regression: $h_{\theta}(x) = \theta_0 + \theta_1 x$.

#### The Cost Function

- $\theta_0$ and $\theta_1$ are the **parameters** of the hypothesis;
- how can we choose the parameters in order to better approximate the input data? We solve a minimisation problem to minimize the **cost function** $J(\theta_0, \theta_1) = \frac{1}{2m} \sum\limits_{i = 1}^m (h^{(i)}_{\theta}(x) - y^{(i)})^2$ (_squared error cost function_, usually the best option for most regression problems);
- cost functions are usually minimised using the **gradient descent** method. Algorithmically, this means to start with a choice of $\theta$ and change them in order to find the minimum of $J(\theta)$.

#### Gradient Descent Method

- from the technical point of view, the gradient descent is: $\theta_j' = \theta_j - \alpha \nabla J(\theta)$ to be repeated until convergence;
- $\alpha$ is called **learning rate** and controls the width of the step towards the minimum (must be $\ge 0$);
- all parameters $\theta_j$ must be updated simultaneously;
- if $\alpha$ is too small, the gradient descent can be very slow;
- if $\alpha$ is too large, the gradient descent can overshoot the real minimum and diverge;
- as we reach the minimum, $\alpha$ does not need to decrease since the derivative of $J$ is already smaller;
- a gradient descent which uses the full set of input features is called **batch gradient descent**.

## Linear Algebra in Octave/MatLab

In [12]:
% create a column vector
v = [ 1;
      2;
      3
    ]

% create a matrix (use , to separate entries in a row and ; to separate columns)
M = [ 1, 2, 3, 4;
      5, 6, 7, 8;
      9, 0, 0, 0
    ]
    
% get the dimensions of v and M
dim_v          = size(v) % method 1: store as [ rows, columns ]
dim_M          = size(M)
[ rowv, colv ] = size(v) % method 2: store rowvs and columns separately
[ rowM, colM ] = size(M)

% refer to a specific element of a vector or matrix (enumeration starts from 1, not 0)
M_31 = M(3,1)
v_1  = v(1)

v =

   1
   2
   3

M =

   1   2   3   4
   5   6   7   8
   9   0   0   0

dim_v =

   3   1

dim_M =

   3   4

rowv =  3
colv =  1
rowM =  3
colM =  4
M_31 =  9
v_1 =  1


In [22]:
% initialise a scalar
s = 3

% multiply a vector or matrix by a scalar
w = s * v
N = s * M

% divide a vector or matrix by a scalar
z = v / s
P = M / s

% add and subtract two vectors or matrices
v + w - z
N + M - P

% N.B.: we can add a scalar to a matrix or vector (as if s = s * I)
v + s
M + s

% compute matrix multiplication
transpose(M) * v
transpose(M) * N

s =  3
w =

   3
   6
   9

N =

    3    6    9   12
   15   18   21   24
   27    0    0    0

z =

   0.33333
   0.66667
   1.00000

P =

   0.33333   0.66667   1.00000   1.33333
   1.66667   2.00000   2.33333   2.66667
   3.00000   0.00000   0.00000   0.00000

ans =

    3.6667
    7.3333
   11.0000

ans =

    3.66667    7.33333   11.00000   14.66667
   18.33333   22.00000   25.66667   29.33333
   33.00000    0.00000    0.00000    0.00000

ans =

   4
   5
   6

ans =

    4    5    6    7
    8    9   10   11
   12    3    3    3

ans =

   38
   14
   17
   20

ans =

   321    96   114   132
    96   120   144   168
   114   144   174   204
   132   168   204   240



In [56]:
% let h1(x) = -0.2 + 0.4 * x, h2(x) = 0.1 + 0.2 * x, h3(x) = 0.5 - 0.1 * x, compute the predictions given some input x
x = [ 123;
      432;
      453
    ];
    
X = [ ones(size(x)), x]
C = [ -0.2, 0.1, 0.5; 0.4, 0.2, -0.1 ]
Y = X * C

X =

     1   123
     1   432
     1   453

C =

  -0.20000   0.10000   0.50000
   0.40000   0.20000  -0.10000

Y =

    49.000    24.700   -11.800
   172.600    86.500   -42.700
   181.000    90.700   -44.800



In [1]:
% special matrices
pkg load statistics

A    = unifrnd(0, 1, [3,3])
trA  = trace(A)
detA = det(A)
invA = pinv(A) % use the pseudoinverse for simplicity and speed (it return the inverse for non singular square matrices)
AT   = A'

A'   == transpose(A)

I = eye(3)

A =

   0.0073865   0.5150664   0.5437590
   0.3176411   0.4142731   0.7174166
   0.6669764   0.6309237   0.5507306

trA =  0.97239
detA =  0.11343
invA =

  -1.97912   0.52376   1.27179
   2.67635  -3.16161   1.47605
  -0.66919   2.98767  -1.41544

AT =

   0.0073865   0.3176411   0.6669764
   0.5150664   0.4142731   0.6309237
   0.5437590   0.7174166   0.5507306

ans =

  1  1  1
  1  1  1
  1  1  1

I =

Diagonal Matrix

   1   0   0
   0   1   0
   0   0   1

